### ISSUE TITLE
Documentation and actual implementation mismatch

### ISSUE THREAD

**Issue by atuljangra** [yask123/RedditWallpapers#1]
<img width="726" alt="screen shot 2016-01-29 at 12 59 55 am" src="https://cloud.githubusercontent.com/assets/1225250/12656329/b124946a-c623-11e5-8d68-c89e5ba70307.png">
In the customizations section, it should be **redditwallpapers**
Also some of the options presented in help menu do not work as specified. Can you check that they are working and possible tell me the correct way.

**Comment by yask123** [comment]
Ah, I see!
Yea, fixing this.
Thanks for reporting.

**Comment by yask123** [comment]
Just updated the module.

Try:

```
pip install redditwallpapers --upgrade 
```

```
 redditwallpapers -sr EarthPorn -sort get_top_from_all -count 40 -t 10
```
