### ISSUE TITLE
OSX installation issue

### ISSUE THREAD

**Issue by RichHatch** [yask123/RedditWallpapers#6]
I installed via pip as described and ran `redditwallpapers` with no arguments.  Got this error

<img width="700" alt="screen shot 2016-01-29 at 7 57 39 am" src="https://cloud.githubusercontent.com/assets/161069/12677380/330501c4-c65e-11e5-8ba9-577ca4243f70.png">

**Comment by yask123** [comment]
Hey!
Thanks for reporting the issue, On it.

**Comment by yask123** [comment]
I believe this is fixed now, 
Can you run 

```
$ pip install redditwallpapers --upgrade
$ redditwallpapers
```

to test it again>

**Comment by RichHatch** [comment]
I'm on a different machine (work, sorry).  But now I'm getting this one

![screen shot 2016-01-29 at 8 58 43 am](https://cloud.githubusercontent.com/assets/161069/12678856/869c0e7e-c666-11e5-9c05-73ab83c63646.png)

**Comment by yask123** [comment]
I believe this is fixed. 
Can you test again?
Sorry for the inconvenience

**Comment by RichHatch** [comment]
Fixed thanks!
